CFLAGS= -Wall -fpic -coverage -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)
#To run playdom you need to entere: ./playdom <any integer number> like ./playdom 10*/
testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc  -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

badTestDrawCard: badTestDrawCard.c dominion.o rngs.o
	gcc -o badTestDrawCard -g  badTestDrawCard.c dominion.o rngs.o $(CFLAGS)

testBuyCard: testDrawCard.c dominion.o rngs.o
	gcc -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

testAll: dominion.o testSuite.c
	gcc -o testSuite testSuite.c -g  dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

runtests: testDrawCard 
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out

unitTest1: unitTest1.c dominion.o rngs.o
	echo "Result for running unitTest1 tests:" > unitTest1.out
	echo "unittest1.c:" >> unitTest1.out
	gcc -o unitTest1 dominion.o rngs.o unitTest1.c $(CFLAGS)
	./unitTest1 >> unitTest1.out
	gcov dominion.c >> unitTest1.out

unit2: unitTest2.c dominion.o rngs.o
	gcc -o unit2 dominion.o rngs.o unitTest2.c $(CFLAGS)

unitTest2: unitTest2.c dominion.o rngs.o
	echo "Result for running unitTest2 tests:" > unitTest2.out
	echo "unittest2.c:" >> unitTest2.out
	gcc -o unitTest2 dominion.o rngs.o unitTest2.c $(CFLAGS)
	./unitTest2 >> unitTest2.out
	gcov dominion.c >> unitTest2.out


player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

all: playdom player 

clean:
	rm -f *.o playdom.exe playdom player player.exe  *.gcov *.gcda *.gcno *.so *.out testDrawCard testDrawCard.exe
